In [67]:
import pandas as pd
from pathlib import Path

# Путь к файлу
file_path = Path('resultik.csv')

# Чтение и фильтрация без вывода
if file_path.exists():
    df = pd.read_csv(file_path)
    # if 'total_hits' in df.columns:
    #     df = df[df['total_hits'] != 0].reset_index(drop=True)
    # else:
    #     df = pd.DataFrame()  # или оставить как есть, если столбца нет
else:
    df = pd.DataFrame()  # пустой DataFrame, если файл не найден

In [68]:
df.sort_values(by='total_hits', ascending=False).head(50)
#df.head(10)

,path,categories,uz,total_hits,ext
2723,ПДнDataset\share\Прочее\Ukaz Prezidenta 226.rtf,"{""обычные"": 811, ""государственные"": 36}",УЗ-2,847,rtf
2060,ПДнDataset\share\Прочее\FZ 273.rtf,"{""обычные"": 811, ""государственные"": 36}",УЗ-2,847,rtf
2535,ПДнDataset\share\Прочее\Prot1_17.10.2024.pdf,"{""обычные"": 5, ""государственные"": 206, ""биомет...",УЗ-1,213,pdf
2536,ПДнDataset\share\Прочее\Prot2_20.02.2025.pdf,"{""обычные"": 5, ""государственные"": 190, ""биомет...",УЗ-1,197,pdf
2233,ПДнDataset\share\Прочее\otbor_k.pdf,"{""обычные"": 179, ""государственные"": 1, ""специа...",УЗ-1,181,pdf
2012,ПДнDataset\share\Прочее\DSUStakeholdersFeedbac...,"{""обычные"": 149}",УЗ-3,149,pdf
2537,ПДнDataset\share\Прочее\Prot3_11.03.2025.pdf,"{""обычные"": 5, ""государственные"": 130, ""специа...",УЗ-1,136,pdf
2794,ПДнDataset\share\Прочее\Координаты для связи с...,"{""обычные"": 102, ""специальные"": 1}",УЗ-1,103,pdf
2538,ПДнDataset\share\Прочее\Prot4_17.07.2025.pdf,"{""обычные"": 3, ""государственные"": 98, ""специал...",УЗ-1,102,pdf
1927,ПДнDataset\share\Прочее\Catalogue_of_UNG_Equip...,"{""обычные"": 87, ""биометрические"": 1}",УЗ-1,88,pdf
2634,ПДнDataset\share\Прочее\sostav_gr.xls,"{""обычные"": 84, ""специальные"": 1}",УЗ-1,85,xls
2986,ПДнDataset\share\Прочее\патентов и ПЭВМ - ЮФУ.pdf,"{""обычные"": 7, ""государственные"": 70, ""биометр...",УЗ-1,79,pdf
2637,ПДнDataset\share\Прочее\spd.docx,"{""обычные"": 77, ""биометрические"": 1, ""специаль...",УЗ-1,79,docx
2179,ПДнDataset\share\Прочее\Media-Kit_KG_2020.pdf,"{""обычные"": 77, ""биометрические"": 1, ""специаль...",УЗ-1,79,pdf
3020,ПДнDataset\share\Прочее\Реестр экскурсоводов 2...,"{""обычные"": 70, ""специальные"": 1}",УЗ-1,71,pdf
1856,ПДнDataset\share\Прочее\AICTE_Mandatory_Disclo...,"{""обычные"": 37, ""государственные"": 10, ""биомет...",УЗ-1,48,pdf
3022,ПДнDataset\share\Прочее\Реестровая выписка л_2...,"{""обычные"": 41, ""государственные"": 2, ""специал...",УЗ-1,44,pdf
2698,ПДнDataset\share\Прочее\Telephone_Directory1.pdf,"{""обычные"": 38, ""биометрические"": 1}",УЗ-1,39,pdf
2239,ПДнDataset\share\Прочее\Otchet_mezhdunarodnaya...,"{""обычные"": 37, ""специальные"": 1}",УЗ-1,38,pdf
2860,ПДнDataset\share\Прочее\П1149_21.05.2025.pdf,"{""обычные"": 17, ""государственные"": 6, ""платёжн...",УЗ-1,36,pdf
2995,ПДнDataset\share\Прочее\ПП_2025_19.01.2025_ито...,"{""обычные"": 27, ""биометрические"": 1, ""специаль...",УЗ-1,29,pdf
1366,ПДнDataset\share\Прочее\%D0%9F%D0%9F_2025_19.0...,"{""обычные"": 27, ""биометрические"": 1, ""специаль...",УЗ-1,29,pdf
2176,ПДнDataset\share\Прочее\mc201308.pdf,"{""обычные"": 28, ""специальные"": 1}",УЗ-1,29,pdf
1341,ПДнDataset\share\Документы партнеров\version-0...,"{""обычные"": 13, ""государственные"": 11, ""платёж...",УЗ-2,26,pdf
1765,ПДнDataset\share\Прочее\49PSMN519.pdf,"{""обычные"": 24, ""государственные"": 1, ""специал...",УЗ-1,26,pdf
2594,ПДнDataset\share\Прочее\requisites.pdf,"{""обычные"": 17, ""государственные"": 5, ""платёжн...",УЗ-2,23,pdf
2174,ПДнDataset\share\Прочее\mc201109.pdf,"{""обычные"": 21}",УЗ-3,21,pdf
2175,ПДнDataset\share\Прочее\mc201205.pdf,"{""обычные"": 20, ""специальные"": 1}",УЗ-1,21,pdf
2518,ПДнDataset\share\Прочее\processing__agreement.pdf,"{""обычные"": 18, ""государственные"": 1, ""биометр...",УЗ-1,21,pdf
3098,ПДнDataset\share\Прочее\Согласие_ПДн_(map.ncpt...,"{""обычные"": 18, ""государственные"": 2}",УЗ-2,20,rtf
2084,ПДнDataset\share\Прочее\Highlights 18.pdf,"{""обычные"": 16}",УЗ-3,16,pdf
2724,ПДнDataset\share\Прочее\Ukaz Prezidenta 364_15...,"{""обычные"": 15, ""государственные"": 1}",УЗ-2,16,rtf
2617,ПДнDataset\share\Прочее\samoobsled_2024.pdf,"{""обычные"": 13, ""биометрические"": 1, ""специаль...",УЗ-1,15,pdf
3026,ПДнDataset\share\Прочее\РУКОВОДСТВО_ПО_БРЕНДИН...,"{""обычные"": 14, ""биометрические"": 1}",УЗ-1,15,pdf
1875,ПДнDataset\share\Прочее\ar_1.pdf,"{""обычные"": 14, ""специальные"": 1}",УЗ-1,15,pdf
1720,ПДнDataset\share\Прочее\42.pdf,"{""обычные"": 13, ""специальные"": 1}",УЗ-1,14,pdf
1365,ПДнDataset\share\Прочее\%D0%9F%D0%90%D0%9C%D0%...,"{""обычные"": 13, ""специальные"": 1}",УЗ-1,14,pdf
1453,ПДнDataset\share\Прочее\%D0%B4%D0%BE%D0%B3%D0%...,"{""обычные"": 9, ""государственные"": 2, ""платёжны...",УЗ-2,14,docx
2629,ПДнDataset\share\Прочее\soglasie_leadplan.pdf,"{""обычные"": 9, ""государственные"": 2, ""биометри...",УЗ-1,13,pdf
1329,ПДнDataset\share\Выгрузки\Сайты\Доки\Terms_of_...,"{""обычные"": 9, ""государственные"": 2, ""биометри...",УЗ-1,13,pdf
1658,ПДнDataset\share\Прочее\2025-2.pdf,"{""обычные"": 10, ""государственные"": 1, ""биометр...",УЗ-1,13,pdf
1339,ПДнDataset\share\Документы партнеров\rules.pdf,"{""обычные"": 11, ""государственные"": 1, ""специал...",УЗ-1,13,pdf
1549,ПДнDataset\share\Прочее\105_order_Spanish_cour...,"{""обычные"": 13}",УЗ-3,13,pdf
3008,ПДнDataset\share\Прочее\Р688.pdf,"{""обычные"": 10, ""государственные"": 1, ""платёжн...",УЗ-1,13,pdf
2719,ПДнDataset\share\Прочее\UGC-Public-Self-Disclo...,"{""обычные"": 12, ""государственные"": 1}",УЗ-2,13,pdf
3021,ПДнDataset\share\Прочее\Реестровая выписка ГА ...,"{""обычные"": 9, ""государственные"": 2, ""специаль...",УЗ-1,12,pdf
1342,ПДнDataset\share\Документы партнеров\version-3...,"{""обычные"": 12}",УЗ-3,12,pdf
2425,ПДнDataset\share\Прочее\PravilaPriema_2025_VO_...,"{""обычные"": 11, ""специальные"": 1}",УЗ-1,12,pdf
1324,ПДнDataset\share\Выгрузки\Сайты\Доки\Privacy_p...,"{""обычные"": 9, ""государственные"": 3}",УЗ-2,12,pdf
2621,ПДнDataset\share\Прочее\SELF_PORTRAIT_english_...,"{""обычные"": 11}",УЗ-3,11,pdf

In [60]:
df.columns

Index(['path', 'categories', 'uz', 'total_hits', 'ext'], dtype='str')

In [69]:
import pandas as pd
import os

# Убедимся, что total_hits — числовой тип
df['total_hits'] = pd.to_numeric(df['total_hits'], errors='coerce')

# Фильтруем строки, где total_hits не равно 0
df_nonzero = df[df['total_hits'] != 0].copy()

# Создаём колонку name, извлекая имя файла из пути
df_nonzero['name'] = df_nonzero['path'].apply(os.path.basename)

# Оставляем только колонку 'name'
result = df_nonzero[['name']].reset_index(drop=True)

In [83]:
result.count

<bound method DataFrame.count of                                                    name
0                                           page_1.html
1                                          page_10.html
2                                         page_101.html
3                                         page_102.html
4                                         page_103.html
...                                                 ...
1090              Согласие законного представителя.docx
1091                   Согласие участника конкурса.docx
1092                    Согласие_ПДн_(map.ncpti.ru).rtf
1093  Филиал в Геленджике декларация на сайт 2016 г....
1094  السيرة الذاتية د. صبحي شرف عميد الكلية 13-3 - ...

[1095 rows x 1 columns]>

In [82]:
result

                                                   name
0                                           page_1.html
1                                          page_10.html
2                                         page_101.html
3                                         page_102.html
4                                         page_103.html
...                                                 ...
1090              Согласие законного представителя.docx
1091                   Согласие участника конкурса.docx
1092                    Согласие_ПДн_(map.ncpti.ru).rtf
1093  Филиал в Геленджике декларация на сайт 2016 г....
1094  السيرة الذاتية د. صبحي شرف عميد الكلية 13-3 - ...

[1095 rows x 1 columns]

In [75]:
result.to_csv('result.csv')